---
- hosts: all

  vars:
   vcenter_hostname: "192.168.0.50"
   vcenter_user: "administrator@vsphere.local"
   vcenter_pass: "Redhat1!"
   guest_name: "cfme058"
   memory: "1024"
   cpu: "1"

  tasks:
  - name: reconfigure CPU and RAM of VM
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ guest_name }}"
      state: "poweredon"
      validate_certs: "false"
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
    delegate_to: "localhost"
